"""add sub_variant table

Revision ID: fabc04990312
Revises: 3beff312d453
Create Date: 2026-08-27 16:37:52.500460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fabc04990312'
down_revision: Union[str, Sequence[str], None] = '3beff312d453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailverification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('otp_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_emailverification_user_id'), 'emailverification', ['user_id'], unique=False)
    op.create_table('productsubvariant',
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['productvariant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'cart', ['id'])
    op.add_column('cartitem', sa.Column('product_sub_variant_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'cartitem', ['id'])
    op.create_foreign_key(None, 'cartitem', 'productsubvariant', ['product_sub_variant_id'], ['id'])
    op.create_unique_constraint(None, 'order', ['id'])
    op.add_column('orderitem', sa.Column('product_sub_variant_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'orderitem', ['id'])
    op.create_foreign_key(None, 'orderitem', 'productsubvariant', ['product_sub_variant_id'], ['id'])
    op.create_unique_constraint(None, 'payment', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'productvariant', ['id'])
    op.create_unique_constraint(None, 'refreshtoken', ['id'])
    op.create_unique_constraint(None, 'refund', ['id'])
    op.create_unique_constraint(None, 'review', ['id'])
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('user', 'email_verified', server_default=sa.false())
    op.add_column('user', sa.Column('total_reviews', sa.Integer(), nullable=False, server_default='0'))
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'webhookevent', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhookevent', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'total_reviews')
    op.drop_column('user', 'email_verified')
    op.drop_constraint(None, 'review', type_='unique')
    op.drop_constraint(None, 'refund', type_='unique')
    op.drop_constraint(None, 'refreshtoken', type_='unique')
    op.drop_constraint(None, 'productvariant', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_constraint(None, 'orderitem', type_='unique')
    op.drop_column('orderitem', 'product_sub_variant_id')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_constraint(None, 'cartitem', type_='foreignkey')
    op.drop_constraint(None, 'cartitem', type_='unique')
    op.drop_column('cartitem', 'product_sub_variant_id')
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_table('productsubvariant')
    op.drop_index(op.f('ix_emailverification_user_id'), table_name='emailverification')
    op.drop_table('emailverification')
    # ### end Alembic commands ###
